name: cancelable
description: cancelletion operation.
version: 0.0.3
homepage: https://github.com/neutronstarer/flutter_cancelable

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
dev_dependencies: